CXX = g++

# fast
CXXFLAGS = -Wall -Wextra -O2 --static -std=c++17 -I /home/pedro/codigos/caderninho/ac-library

# debug
CXXFLAGS = -fsanitize=address,undefined -fno-omit-frame-pointer -g -Wall -Wshadow -std=c++17 -Wno-unused-result -Wno-sign-compare -Wno-char-subscripts -I /home/pedro/codigos/caderninho/ac-library #-fuse-ld=gold

